sudo: required
language: generic
services:
  - docker
# test -> build -> push to docker hub and wait for hosting
before_install:
  #Build Context in ./client
  - docker build -t frankypassword123/listingapp-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true frankypassword123/listingapp-test npm test

after_success:
  - docker build -t frankypassword123/listingapp-client ./client
  - docker build -t frankypassword123/listingapp-nginx ./nginx
  - docker build -t frankypassword123/listingapp-server ./backend

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push frankypassword123/listingapp-client
  - docker push frankypassword123/listingapp-nginx
  - docker push frankypassword123/listingapp-server

# Config of aws for deploying image to to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'listingapp'
  env: 'Listingapp-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-073032805649'
  bucket_path: 'listingapp-fullstack'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
